Add new command handler
Minehut/MinehutBOTOld pull request #6
Opened 2017-04-27 07:04 UTC by MatrixTunnel

Thank you @xaoseric for redoing this

2017-04-27 07:05 UTC, MatrixTunnel commented
@xaoseric Do you approve of this PR and the changes I have made to your code?

2017-04-27 11:31 UTC, randomnetcat requested changes
Okay, this is what I've found so far, there might be more that I haven't looked at, but can't look atm.

2017-04-27 11:31 UTC, meowingtwurtle commented on src/main/java/com/minehut/discordbot/commands/CommandHandler.java
> +                if (user.getId().equals(id) && !GuildSettings.isTrusted(sender)) {
Just use Core.getConfig().getBlockedUsers().contains(user.getId()) with trusted check and drop the forloop

2017-04-27 11:31 UTC, meowingtwurtle commented on src/main/java/com/minehut/discordbot/commands/CommandHandler.java
> +                    Chat.sendMessage(user.getAsMention() + " You are blacklisted from using bot commands. If you believe this is an error, please contact MatrixTunnel.", channel, 10);
This could either send out this message, just ignore the command, or send it to DM.

I vote for one of the latter two, just to prevent spam

2017-04-27 11:31 UTC, meowingtwurtle commented on src/main/java/com/minehut/discordbot/commands/CommandHandler.java
> +            if (botCmd == null) { // this shouldn't happen, it only uses registered commands but incase.
This could happen if someone mistypes the command

2017-04-27 11:31 UTC, meowingtwurtle commented on src/main/java/com/minehut/discordbot/commands/CommandHandler.java
> +    protected Command getCommand(String name) {
Other things could have uses for this, like, in the future, getEnabled/setEnabled

2017-04-27 11:31 UTC, meowingtwurtle commented on src/main/java/com/minehut/discordbot/commands/Command.java
> +    private String name;
This could be merged with aliases as the first item, then just return aliases[0] in getName()

2017-04-27 11:31 UTC, meowingtwurtle commented on src/main/java/com/minehut/discordbot/commands/Command.java
> +        return name;
see above

2017-04-27 11:31 UTC, meowingtwurtle commented on src/main/java/com/minehut/discordbot/commands/general/InfoCommand.java
> +    public boolean onCommand(Guild guild, TextChannel channel, Member sender, Message message, String[] args) throws CommandException {
This could invoke the other command just so people don't have to retype it all again, then eventually removed

2017-04-27 11:31 UTC, meowingtwurtle commented on src/main/java/com/minehut/discordbot/commands/general/minehut/StatusCommand.java
>                      if (!sender.getUser().getId().equals("118088732753526784")) {
Comment with why this user or make this a constant

2017-04-27 15:36 UTC, xaoseric commented
yes @MatrixTunnel I approve of the pull, I've been experimenting with GuildConfigs, and i'll send another your way soon :)

2017-04-27 17:01 UTC, MatrixTunnel commented on src/main/java/com/minehut/discordbot/commands/CommandHandler.java
> +                if (user.getId().equals(id) && !GuildSettings.isTrusted(sender)) {
Since this is a string array, it doesn't allow you to do that. I'm going to change it to a string list

2017-04-27 17:40 UTC, MatrixTunnel commented on src/main/java/com/minehut/discordbot/commands/Command.java
> +    private String name;
I actually changed how this works a bit with my latest commit. I recommend you check it out [here](https://github.com/Minehut/MinehutBOT/pull/6/commits/552f23ac5ce7fc23462ea4d6477c6da1ffbb2336)

2017-04-27 17:41 UTC, MatrixTunnel commented on src/main/java/com/minehut/discordbot/commands/Command.java
> +    private String name;
I actually changed how this works a bit with my latest commit. I recommend you check it out [here](https://github.com/Minehut/MinehutBOT/pull/6/commits/552f23ac5ce7fc23462ea4d6477c6da1ffbb2336)

2017-04-27 17:42 UTC, MatrixTunnel commented on src/main/java/com/minehut/discordbot/commands/general/InfoCommand.java
> +    public boolean onCommand(Guild guild, TextChannel channel, Member sender, Message message, String[] args) throws CommandException {
I'm just going to remove this since most people have switched over already

2017-04-27 18:04 UTC, MatrixTunnel commented
@meowingtwurtle I changed some things around so I recommend taking a look at it again

2017-04-27 21:03 UTC, meowingtwurtle commented on src/main/java/com/minehut/discordbot/commands/CommandHandler.java
> +                if (user.getId().equals(id) && !GuildSettings.isTrusted(sender)) {
Oh sorry, thought it was a List :P

2017-04-27 21:04 UTC, meowingtwurtle commented on src/main/java/com/minehut/discordbot/commands/CommandHandler.java
> +            if (cmd == null) { // this shouldn't happen, it only uses registered commands but incase.
Why couldn't this happen? What if someone mistypes a command?

2017-04-27 21:18 UTC, MatrixTunnel commented
Looks like we're done here :)

2017-04-27 21:20 UTC, merged

2019-06-21 21:14 UTC, Sniped commented
this has already been an added feature, [here](https://github.com/Sniped/MinehutBOT/blob/master/commands/infraction.js#L71) you can find the code for that, in the future i will make it so you can set punishments to permanent